### ISSUE TITLE
env::var_os("RUST_BACKTRACE") should only be called once.

### ISSUE THREAD

**Issue by eddyb** [rust-lang-nursery/error-chain#207]
The caching can be done with just an `AtomicBool` (thanks, @edef1c!).
I'm seeing something like a hundred thousand allocations from this, per second, and C calls, of course, and none of those are really needed (they might be small but they're profiling noise).

**Comment by Yamakaky** [comment]
I don't think it's checked in this crate?

**Comment by eddyb** [comment]
It's in `lib.rs` last I looked.

**Comment by Yamakaky** [comment]
Right! Do you want to try a PR?

**Comment by eddyb** [comment]
@Yamakaky Ended up doing it, see #210.

**Comment by Arnavion** [comment]
This can be closed now, right?

**Comment by eddyb** [comment]
Right, thanks for the reminder!
