### ISSUE TITLE
Release 0.11.0?

### ISSUE THREAD

**Issue by faern** [rust-lang-nursery/error-chain#215]
Quite a lot changed since 0.10.0, and the `warning: doc comment not used by rustdoc` in 0.10.0 on nightly is mighty annoying. Would be nice to have a version that fixes that.

I would suggest waiting for #210 and #193 because they are done, they should just be merged. Is there some other feature you are waiting for that is planned for 0.11.0, or can it just be released?

**Comment by Yamakaky** [comment]
SGTM.

**Comment by Yamakaky** [comment]
Should be good, just waiting for travis to finish the tests.

**Comment by Yamakaky** [comment]
Done!
