### ISSUE TITLE
warning: lint unused_doc_comment has been renamed to unused_doc_comments

### ISSUE THREAD

**Issue by df5602** [rust-lang-nursery/error-chain#245]
If you use the `error_chain!` macro on a recent nightly, a number of warnings are generated:

```
warning: lint unused_doc_comment has been renamed to unused_doc_comments
 --> src/main.rs:4:1
  |
4 | / error_chain! {
5 | |     foreign_links {
6 | |         IoError(::std::io::Error);
7 | |     }
8 | | }
  | |_^
  |
  = note: #[warn(renamed_and_removed_lints)] on by default
  = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```
([Playground](https://play.rust-lang.org/?gist=a605946597f259a71b86b0ae7d975caf&version=nightly&mode=debug))

I think, this is due to [#50879](https://github.com/rust-lang/rust/pull/50879).

I'm not sure how to correctly fix this, since just replacing `#[allow(unused_doc_comment)]` with `#[allow(unused_doc_comments)]` will not work on older compilers (including current stable).

**Comment by hoodie** [comment]
how about this #246

**Comment by jamesray1** [comment]
+1
https://github.com/Drops-of-Diamond/diamond_drops/issues/86

**Comment by Yamakaky** [comment]
Done

**Comment by dwijnand** [comment]
@Yamakaky the 0.12.0 tag seems to be missing in https://github.com/rust-lang-nursery/error-chain/tags
