### ISSUE TITLE
error-chain seems to have a problem with rust 1.27

### ISSUE THREAD

**Issue by mark-summerfield** [rust-lang-nursery/error-chain#249]
error-chain seems to produce compiler warnings with rust 1.27 (and no warnings with 1.2[4-6]).
I don't really understand what the problem is, but it seems to be genuine. See this thread (2nd and subsequent messages): [rust-users](https://users.rust-lang.org/t/rust-1-27-0-is-out/18233).

**Comment by Yamakaky** [comment]
Closing for https://github.com/rust-lang-nursery/error-chain/issues/245, release in progress
