### ISSUE TITLE
Importing the macro Rust 2018 way

### ISSUE THREAD

**Issue by myfreeweb** [rust-lang-nursery/error-chain#250]
Looks like it's not possible to [`use` the `error_chain` macro](https://rust-lang-nursery.github.io/edition-guide/2018/transitioning/modules/macros.html) as it's defined in a private module...

**Comment by Procrat** [comment]
It looks like it works when you do this:
```rust
    use error_chain::error_chain;
    use error_chain::error_chain_processing;
    use error_chain::impl_error_chain_processed;
    use error_chain::impl_error_chain_kind;
    use error_chain::impl_extract_backtrace;

    error_chain! {
         ...
    }
```
(Definitely not saying you should do that, but at least you can make it compile now.)

**Comment by joepie91** [comment]
The ergonomics problem here is described more in [this post](https://users.rust-lang.org/t/2018-edition-macro-ergonomics/18790/2), along with a solution that apparently needs to be implemented by `error-chain` itself.
