### ISSUE TITLE
cargo publish error

### ISSUE THREAD

**Issue by AndyGauge** [rust-lang-nursery/error-chain#259]
Uploading error-chain v0.12.1-rc.1 (/home/andy/git/error-chain)
error: api errors (status 200 OK): this crate exists but you don't seem to be an owner. If you believe this is a mistake, perhaps you need to accept an invitation to be an owner before publishing.

**Comment by KodrAus** [comment]
Ah I’m not an owner of this crate so unfortunately I can’t add you.

cc @alexcrichton would it be possible to add @AndyGauge as an owner for `error-chain` on crates.io?

**Comment by Yamakaky** [comment]
Sent you an invite on crates.io

**Comment by AndyGauge** [comment]
Thank you
